version: 2.0

jobs:
  install:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-
      - run:
          name: Install tox
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install tox
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

  flake:
    steps:
      - run:
        name: Flake 8
        command:
          tox -e flake8

  nose:
    steps:
      - run:
        name: Test 3.6
        command:
          tox -e py36

  coverage:
    steps:
      - run:
        name: Coverage
        command:
          tox -e coverage
          tox -e codacy
          tox -e codecov

workflows:
  version: 2
  build:
    jobs:
      - install
      - flake:
        requires:
          - install
      - nose:
        requires:
          - install
